import { StyleSheet } from '@react-pdf/renderer';
const stylesPdf = StyleSheet.create({
  body: {
    paddingTop: 25,
    //paddingBottom: 65,
    paddingHorizontal: 25,
  },
  page: {
    padding: 40,
  },
  header: {
    gap: '10px',
    fontSize: 12,
    //marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    backgroundColor: '#f8d2f8',
    paddingHorizontal: '20px',
    borderRadius: '8px',
  },
  footer: {
    position: 'relative',
    // top: '40px',
    // left: '40px',
    width: '100%',
    gap: '5px',
    fontSize: 12,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    backgroundColor: '#f8d2f8',
    padding: '10px',
    borderRadius: '8px',
  },
  title: {
    fontSize: 15,
    //textAlign: 'left',
    fontFamily: 'Helvetica',
    //marginBottom: 10,
  },
  text: {
    fontFamily: 'Helvetica',
    fontSize: 8,
    marginBottom: 5,
    width: '100%',
  },
  textName: {
    fontSize: 9,
    marginBottom: 5,
    fontFamily: 'Helvetica-Bold',
    maxWidth: '100%',
    display: 'flex',
    flexWrap: 'wrap',
  },
  rectangleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    //alignContent: 'flex-start',
    //justifyContent: 'center',
    marginBottom: '200px',
    //alignItems: 'flex-start',
  },
  cell: {
    width: '24%',
    borderWidth: 1,
    borderColor: '#000',
    padding: 5,
    display: 'flex',
    flexDirection: 'row',
  },
  decuria: {
    margin: 6,
    marginTop: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  image: { height: 60 },
  imageEvent: {
    width: '30%',
    height: '100%',
    objectFit: 'cover',
  },
  imageDecuria: { height: 30 },
  columnUser: {
    flexDirection: 'column',
    width: '70%',
    justifyContent: 'center',
  },
});
export { stylesPdf };
