import { StyleSheet } from '@react-pdf/renderer';
const stylesPdf = StyleSheet.create({
  body: {
    paddingTop: 25,
    paddingHorizontal: 25,
    paddingBottom: '80px',
  },
  bodyCover: {
    paddingVertical: 15,
    paddingHorizontal: 15,
  },
  page: {
    padding: 40,
  },
  header: {
    gap: '10px',
    fontSize: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    // backgroundColor: '#f8d2f8',
    // backgroundColor: '#e4e0dc',
    // paddingHorizontal: '20px',
    borderRadius: '8px',
    height: '125px',
    width: '100%',
    //backgroundColor: '#97E1E2',
    // backgroundColor: '#B2E3E3',
  },
  imageBackground: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    objectFit: 'fill',
    // opacity: 0.1,
    borderRadius: '8px',
  },
  footer: {
    position: 'absolute',
    top: '520px',
    left: '25px',
    width: '100%',
    gap: '5px',
    fontSize: 12,
    marginBottom: 10,
    height: '50px',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    //backgroundColor: '#f8d2f8',
    // backgroundColor: '#B2E3E3',
    // padding: '10px',
    borderRadius: '8px',
  },
  cover: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
    width: '100%',
    height: '100%',
    // backgroundColor: '#B2E3E3',
  },
  title: {
    fontSize: 15,
    fontFamily: 'Helvetica',
  },
  text: {
    fontFamily: 'Helvetica',
    fontSize: 8,
    marginBottom: 5,
    width: '100%',
  },
  textName: {
    fontSize: 9,
    marginBottom: 5,
    fontFamily: 'Helvetica-Bold',
    maxWidth: '100%',
    display: 'flex',
    flexWrap: 'wrap',
  },
  rectangleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: '60px', //muda essa linha sempre que mudar altura ou largura de algo
  },
  cell: {
    width: '24%',
    borderWidth: 1,
    borderColor: '#000',
    padding: 3,
    display: 'flex',
    flexDirection: 'row',
  },
  decuria: {
    //   minHeight:"80%",
    margin: 6,
    marginTop: 10,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  imagePhoto: { height: 60, width: 50, objectFit: 'cover', marginRight: 5 },
  image: { height: 50 },
  imageCover: { height: '100%' },
  imageFooter: {
    height: 40,
    width: '100%',
    // height: '100%',
    objectFit: 'cover',
    // opacity: 0.1,
    borderRadius: '8px',
  },
  imageEvent: {
    width: '25%',
    objectFit: 'fill',
  },
  imageDecuria: { height: 30 },
  columnUser: {
    flexDirection: 'column',
    width: '70%',
    justifyContent: 'center',
  },
});
export { stylesPdf };
