import { StyleSheet } from '@react-pdf/renderer';
const stylesPdf = StyleSheet.create({
  body: {
    paddingTop: 25,
    paddingHorizontal: 25,
    paddingBottom: '80px',
  },
  page: {
    padding: 40,
  },
  header: {
    gap: '10px',
    fontSize: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    // backgroundColor: '#f8d2f8',
    paddingHorizontal: '20px',
    borderRadius: '8px',
    height: '125px',
    //backgroundColor: '#97E1E2',
    backgroundColor: '#B2E3E3',
  },
  footer: {
    position: 'absolute',
    top: '520px',
    left: '25px',
    width: '100%',
    gap: '5px',
    fontSize: 12,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    //backgroundColor: '#f8d2f8',
    backgroundColor: '#B2E3E3',
    padding: '10px',
    borderRadius: '8px',
  },
  cover: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
    width: '100%',
    height: '100%',
    backgroundColor: '#B2E3E3',
  },
  title: {
    fontSize: 15,
    fontFamily: 'Helvetica',
  },
  text: {
    fontFamily: 'Helvetica',
    fontSize: 8,
    marginBottom: 5,
    width: '100%',
  },
  textName: {
    fontSize: 9,
    marginBottom: 5,
    fontFamily: 'Helvetica-Bold',
    maxWidth: '100%',
    display: 'flex',
    flexWrap: 'wrap',
  },
  rectangleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: '80px',//muda essa linha sempre que mudar altura ou largura de algo
  },
  cell: {
    width: '24%',
    borderWidth: 1,
    borderColor: '#000',
    padding: 3,
    display: 'flex',
    flexDirection: 'row',
  },
  decuria: {
 //   minHeight:"80%",
    margin: 6,
    marginTop: 10,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  image: { height: 50 },
  imageCover: { height: '60%' },
  imageFooter: { height: 40 },
  imageEvent: {
    width: '20%',
    objectFit: 'fill',
  },
  imageDecuria: { height: 30 },
  columnUser: {
    flexDirection: 'column',
    width: '70%',
    justifyContent: 'center',
  },
});
export { stylesPdf };
