import { StyleSheet } from '@react-pdf/renderer';
const stylesPdfRooms = StyleSheet.create({
  body: {
    paddingTop: 25,
    paddingHorizontal: 40,
    paddingBottom: '80px',
  },
  page: {
    padding: 40,
  },
  header: {
    gap: '10px',
    fontSize: 12,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    // backgroundColor: '#f8d2f8',
    paddingHorizontal: '20px',
    borderRadius: '8px',
    height: '125px',
  },
  title: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
  },
  subTitle: {
    fontSize: 16,
    fontFamily: 'Helvetica',
  },
  text: {
    fontFamily: 'Helvetica',
    fontSize: 8,
    padding: 3,
    width: '100%',
  },
  textName: {
    fontSize: 16,
    padding: 3,
    fontFamily: 'Helvetica',
    maxWidth: '100%',
    display: 'flex',
    flexWrap: 'wrap',
  },
  textNameBold: {
    fontSize: 16,
    padding: 3,
    fontFamily: 'Helvetica-Bold',
    maxWidth: '100%',
    display: 'flex',
    flexWrap: 'wrap',
  },
  containerRow: {
    //flexDirection: 'row',
    //flexWrap: 'wrap',
    width: 'auto',
    gap: -1,
    marginTop: 10,
    marginBottom: '200px',
  },
  row: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: -1,
  },
  cell: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#000',
    //padding: 3,
    display: 'flex',
    flexDirection: 'row',
  },
  decuria: {
    // margin: 6,
    marginTop: 10,
    gap: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'column',
  },
  image: { height: 40 },
  imageEvent: {
    // height: '70%',
    height: 60,
    objectFit: 'fill',
  },
});
export { stylesPdfRooms };
